INSERT INTO relationships (id, type, subtype, name, side_a, side_b, status, intensity, since, notes) VALUES
('rel_001', 'alliance', 'military', 'North Atlantic Treaty Organization (NATO)', '{ALB,BEL,BGR,CAN,HRV,CZE,DNK,EST,FIN,FRA,DEU,GRC,HUN,ISL,ITA,LVA,LTU,LUX,MNE,NLD,MKD,NOR,POL,PRT,ROU,SVK,SVN,ESP,SWE,TUR,GBR,USA}', NULL, 'active', 'high', '1949-04-04', 'Collective defense alliance under Article 5'),
('rel_002', 'alliance', 'military', 'Collective Security Treaty Organization (CSTO)', '{ARM,BLR,KAZ,KGZ,RUS,TJK}', NULL, 'active', 'high', '2002-10-07', 'Post-Soviet collective defense alliance'),
('rel_003', 'alliance', 'military', 'AUKUS', '{AUS,GBR,USA}', NULL, 'active', 'high', '2021-09-15', 'Defense and advanced military technology partnership'),
('rel_004', 'alliance', 'military', 'ANZUS', '{AUS,NZL,USA}', NULL, 'active', 'medium', '1951-09-01', 'Security treaty; military cooperation remains active'),
('rel_005', 'alliance', 'military', 'Five Power Defence Arrangements', '{AUS,GBR,MYS,NZL,SGP}', NULL, 'active', 'medium', '1971-11-01', 'Consultative defense arrangement for Malaysia and Singapore'),
('rel_006', 'alliance', 'military', 'US-Japan Security Treaty', '{USA,JPN}', NULL, 'active', 'high', '1960-06-23', 'Mutual defense treaty and US force presence'),
('rel_007', 'alliance', 'military', 'US-South Korea Mutual Defense Treaty', '{USA,KOR}', NULL, 'active', 'high', '1953-10-01', 'Mutual defense commitment on Korean Peninsula'),
('rel_008', 'alliance', 'military', 'US-Philippines Mutual Defense Treaty', '{USA,PHL}', NULL, 'active', 'high', '1951-08-30', 'Mutual defense treaty in Indo-Pacific'),
('rel_009', 'alliance', 'military', 'US-Thailand Alliance', '{THA,USA}', NULL, 'active', 'medium', '1954-09-08', 'Major non-NATO ally with defense commitments'),
('rel_010', 'alliance', 'military', 'US-Australia Defense Alliance', '{AUS,USA}', NULL, 'active', 'high', '1951-09-01', 'Bilateral defense obligations under ANZUS framework'),
('rel_011', 'alliance', 'military', 'US-New Zealand Defense Cooperation', '{NZL,USA}', NULL, 'active', 'medium', '2010-11-04', 'Renewed strategic defense partnership'),
('rel_012', 'alliance', 'military', 'US-Taiwan Security Commitment', '{TWN,USA}', NULL, 'active', 'medium', '1979-01-01', 'Security guarantees under Taiwan Relations Act'),
('rel_013', 'alliance', 'military', 'China-North Korea Mutual Aid Treaty', '{CHN,PRK}', NULL, 'active', 'high', '1961-07-11', 'Mutual defense treaty between Beijing and Pyongyang'),
('rel_014', 'alliance', 'military', 'Russia-Belarus Union State Defense Agreement', '{BLR,RUS}', NULL, 'active', 'high', '1999-12-08', 'Integrated military and air defense structures'),
('rel_015', 'alliance', 'military', 'Russia-Abkhazia Defense Agreement', '{RUS,ABK}', NULL, 'active', 'medium', '2014-11-24', 'Joint defense and military integration'),
('rel_016', 'alliance', 'military', 'Russia-South Ossetia Defense Agreement', '{RUS,OST}', NULL, 'active', 'medium', '2015-03-18', 'Joint defense and security integration'),
('rel_017', 'alliance', 'military', 'France-Monaco Defense Treaty', '{FRA,MCO}', NULL, 'active', 'medium', '2002-10-24', 'France guarantees Monaco defense'),
('rel_018', 'alliance', 'military', 'France-Andorra Defense Arrangement', '{AND,FRA}', NULL, 'active', 'low', '1993-01-01', 'France participates in Andorra security guarantee'),
('rel_019', 'alliance', 'military', 'Spain-Andorra Defense Arrangement', '{AND,ESP}', NULL, 'active', 'low', '1993-01-01', 'Spain participates in Andorra security guarantee'),
('rel_020', 'alliance', 'military', 'Australia-Papua New Guinea Bilateral Security Treaty', '{AUS,PNG}', NULL, 'active', 'medium', '2023-12-07', 'Framework for defense cooperation and assistance'),
('rel_021', 'alliance', 'military', 'Australia-Japan Reciprocal Access Agreement', '{AUS,JPN}', NULL, 'active', 'medium', '2022-01-06', 'Defense cooperation and military access framework'),
('rel_022', 'alliance', 'military', 'Japan-United Kingdom Hiroshima Accord', '{GBR,JPN}', NULL, 'active', 'medium', '2023-05-18', 'Enhanced defense and security cooperation'),
('rel_023', 'alliance', 'military', 'United Kingdom-Poland Mutual Defense Treaty', '{GBR,POL}', NULL, 'active', 'medium', '2017-12-21', 'Bilateral defense and security cooperation'),
('rel_024', 'alliance', 'military', 'Greece-France Strategic Defense Partnership', '{FRA,GRC}', NULL, 'active', 'high', '2021-09-28', 'Includes mutual defense assistance clause'),
('rel_025', 'alliance', 'military', 'Turkey-Azerbaijan Shusha Declaration', '{AZE,TUR}', NULL, 'active', 'high', '2021-06-15', 'Mutual military assistance and cooperation'),
('rel_026', 'alliance', 'military', 'Russia-Armenia Defense Treaty', '{ARM,RUS}', NULL, 'active', 'medium', '1997-08-29', 'Bilateral military alliance and basing rights'),
('rel_027', 'alliance', 'military', 'India-Bhutan Security Partnership', '{BTN,IND}', NULL, 'active', 'medium', '1949-08-08', 'India supports Bhutan external security'),
('rel_028', 'alliance', 'military', 'India-Nepal Treaty of Peace and Friendship', '{IND,NPL}', NULL, 'active', 'low', '1950-07-31', 'Security cooperation and mutual consultation'),
('rel_029', 'alliance', 'military', 'US-Bahrain Defense Cooperation Agreement', '{BHR,USA}', NULL, 'active', 'medium', '1991-10-28', 'Strategic defense cooperation and basing'),
('rel_030', 'alliance', 'military', 'US-Kuwait Defense Cooperation Agreement', '{KWT,USA}', NULL, 'active', 'medium', '1991-09-19', 'Defense cooperation and military presence'),
('rel_031', 'alliance', 'military', 'US-Qatar Defense Cooperation Agreement', '{QAT,USA}', NULL, 'active', 'medium', '1992-06-23', 'Military cooperation and strategic basing'),
('rel_032', 'alliance', 'military', 'US-United Arab Emirates Defense Partnership', '{ARE,USA}', NULL, 'active', 'medium', '1994-07-25', 'Defense cooperation and military access'),
('rel_033', 'alliance', 'military', 'US-Israel Strategic Defense Partnership', '{ISR,USA}', NULL, 'active', 'high', '2014-12-19', 'Strategic military cooperation and security guarantees'),
('rel_034', 'alliance', 'military', 'Russia-Tajikistan Defense Agreement', '{RUS,TJK}', NULL, 'active', 'medium', '2012-10-05', 'Russian military presence and defense cooperation'),
('rel_035', 'alliance', 'military', 'Russia-Kyrgyzstan Defense Agreement', '{KGZ,RUS}', NULL, 'active', 'medium', '2012-09-20', 'Military basing and defense cooperation'),
('rel_036', 'war', 'international', 'Russia-Ukraine War', '{RUS}', '{UKR}', 'active', 'high', '2022-02-24', 'Large-scale interstate war across Ukrainian territory'),
('rel_037', 'war', 'international', 'Israel-Hamas War', '{ISR}', '{PSE}', 'active', 'high', '2023-10-07', 'War centered on Gaza Strip and southern Israel'),
('rel_038', 'conflict', 'international', 'Israel-Hezbollah Conflict', '{ISR}', '{LBN}', 'active', 'medium', '2023-10-08', 'Cross-border hostilities remain ongoing'),
('rel_039', 'war', 'civil_war', 'Sudanese Civil War', '{SDN}', '{RSF}', 'active', 'high', '2023-04-15', 'Nationwide war between SAF and Rapid Support Forces'),
('rel_040', 'war', 'civil_war', 'Myanmar Civil War', '{MMR}', '{PDF}', 'active', 'high', '2021-02-01', 'Military junta fights resistance and ethnic forces'),
('rel_041', 'conflict', 'civil_war', 'Syrian Civil War', '{SYR}', '{SNA,SDF,HTS}', 'active', 'medium', '2011-03-15', 'Fragmented conflict with foreign involvement'),
('rel_042', 'conflict', 'international', 'DR Congo-M23 Conflict', '{COD}', '{M23}', 'active', 'high', '2021-11-07', 'Eastern Congo conflict with regional implications'),
('rel_043', 'conflict', 'civil_war', 'Somalia Insurgency', '{SOM}', '{ALS}', 'active', 'high', '2006-01-01', 'Government battles Al-Shabaab insurgency'),
('rel_044', 'conflict', 'civil_war', 'Sahel Jihadist Insurgency', '{MLI,BFA,NER}', '{JNM,ISW}', 'active', 'high', '2012-01-01', 'Regional insurgency across central Sahel'),
('rel_045', 'conflict', 'civil_war', 'Lake Chad Insurgency', '{NGA,NER,TCD,CMR}', '{BOK,ISW}', 'active', 'medium', '2009-07-26', 'Boko Haram and ISWAP insurgency'),
('rel_046', 'conflict', 'civil_war', 'Yemen Civil War', '{YEM,SAU}', '{HOU}', 'active', 'medium', '2014-09-21', 'Reduced intensity but conflict remains unresolved'),
('rel_047', 'conflict', 'international', 'Red Sea Crisis', '{USA,GBR,ISR}', '{HOU}', 'active', 'medium', '2023-11-19', 'Attacks on shipping and retaliatory strikes'),
('rel_048', 'conflict', 'civil_war', 'Ethiopian Oromia Conflict', '{ETH}', '{OLA}', 'active', 'medium', '2018-01-01', 'Insurgency in Oromia region'),
('rel_049', 'conflict', 'civil_war', 'Ethiopian Amhara Conflict', '{ETH}', '{FAN}', 'active', 'medium', '2023-08-01', 'Armed clashes in Amhara region'),
('rel_050', 'conflict', 'civil_war', 'Pakistan Insurgency', '{PAK}', '{TTP,BLA}', 'active', 'medium', '2004-01-01', 'Militant violence in northwest and Balochistan'),
('rel_051', 'conflict', 'civil_war', 'Baloch Insurgency', '{PAK}', '{BLA,BLF}', 'active', 'medium', '2004-01-01', 'Separatist insurgency in Balochistan'),
('rel_052', 'conflict', 'civil_war', 'Indian Maoist Insurgency', '{IND}', '{CPI}', 'active', 'low', '2004-09-21', 'Naxalite insurgency continues in central India'),
('rel_053', 'conflict', 'civil_war', 'Kashmir Armed Conflict', '{IND}', '{MIL}', 'active', 'medium', '1989-01-01', 'Insurgency and cross-border militant activity'),
('rel_054', 'conflict', 'international', 'India-Pakistan Line of Control Conflict', '{IND}', '{PAK}', 'active', 'low', '1947-10-22', 'Periodic military incidents along LoC'),
('rel_055', 'conflict', 'civil_war', 'Philippines Communist Insurgency', '{PHL}', '{NPA}', 'active', 'low', '1969-03-29', 'Long-running communist rebellion'),
('rel_056', 'conflict', 'civil_war', 'Philippines Moro Insurgency', '{PHL}', '{ASG}', 'active', 'low', '1991-01-01', 'Residual Islamist insurgent activity'),
('rel_057', 'conflict', 'civil_war', 'Colombian Armed Conflict', '{COL}', '{EMC,ELN}', 'active', 'medium', '1964-05-27', 'Guerrilla and criminal armed groups remain active'),
('rel_058', 'conflict', 'civil_war', 'Haiti Gang War', '{HTI}', '{G9,VIV}', 'active', 'high', '2020-01-01', 'Armed gangs control significant territory'),
('rel_059', 'conflict', 'civil_war', 'Cameroon Anglophone Crisis', '{CMR}', '{ASC}', 'active', 'medium', '2017-10-01', 'Separatist conflict in Northwest and Southwest'),
('rel_060', 'conflict', 'civil_war', 'Mozambique Cabo Delgado Insurgency', '{MOZ,RWA}', '{ISC}', 'active', 'medium', '2017-10-05', 'Islamist insurgency in northern Mozambique'),
('rel_061', 'conflict', 'civil_war', 'Central African Republic Conflict', '{CAF}', '{CPC}', 'active', 'medium', '2012-12-10', 'Government faces multiple rebel coalitions'),
('rel_062', 'conflict', 'civil_war', 'South Sudan Communal Conflict', '{SSD}', '{MIL}', 'active', 'medium', '2018-09-12', 'Persistent armed violence despite peace accords'),
('rel_063', 'conflict', 'civil_war', 'Paraguay EPP Insurgency', '{PRY}', '{EPP}', 'active', 'low', '2008-01-01', 'Small-scale insurgency in northern Paraguay'),
('rel_064', 'conflict', 'international', 'Turkey-PKK Conflict', '{TUR}', '{PKK}', 'active', 'medium', '1984-08-15', 'Cross-border operations in Iraq and Syria'),
('rel_065', 'conflict', 'international', 'Iran-Israel Shadow War', '{IRN}', '{ISR}', 'active', 'medium', '2018-01-01', 'Indirect military confrontation across region'),
('rel_066', 'rivalry', 'geopolitical', 'United States-China Rivalry', '{USA}', '{CHN}', 'active', 'high', '2017-01-20', 'Global competition in security, technology and influence'),
('rel_067', 'rivalry', 'geopolitical', 'United States-Russia Rivalry', '{USA}', '{RUS}', 'active', 'high', '2014-02-20', 'Strategic confrontation over security and global order'),
('rel_068', 'rivalry', 'geopolitical', 'China-India Rivalry', '{CHN}', '{IND}', 'active', 'high', '1962-10-20', 'Border disputes and regional power competition'),
('rel_069', 'rivalry', 'geopolitical', 'India-Pakistan Rivalry', '{IND}', '{PAK}', 'active', 'high', '1947-08-15', 'Strategic rivalry centered on Kashmir and security'),
('rel_070', 'rivalry', 'geopolitical', 'Iran-Israel Rivalry', '{IRN}', '{ISR}', 'active', 'high', '1979-02-11', 'Regional confrontation involving proxies and deterrence'),
('rel_071', 'rivalry', 'geopolitical', 'Iran-Saudi Arabia Rivalry', '{IRN}', '{SAU}', 'active', 'medium', '1979-02-11', 'Competition for influence across Middle East'),
('rel_072', 'rivalry', 'geopolitical', 'Turkey-Greece Rivalry', '{GRC}', '{TUR}', 'active', 'medium', '1974-07-20', 'Aegean, Cyprus and maritime disputes'),
('rel_073', 'rivalry', 'geopolitical', 'Armenia-Azerbaijan Rivalry', '{ARM}', '{AZE}', 'active', 'high', '1988-02-20', 'Post-Karabakh tensions and border disputes'),
('rel_074', 'rivalry', 'geopolitical', 'Morocco-Algeria Rivalry', '{DZA}', '{MAR}', 'active', 'high', '1963-10-08', 'Regional competition and Western Sahara issue'),
('rel_075', 'rivalry', 'geopolitical', 'North Korea-South Korea Rivalry', '{PRK}', '{KOR}', 'active', 'high', '1953-07-27', 'Military confrontation across the DMZ'),
('rel_076', 'rivalry', 'geopolitical', 'China-Japan Rivalry', '{CHN}', '{JPN}', 'active', 'medium', '2010-09-07', 'Strategic and maritime competition in East Asia'),
('rel_077', 'rivalry', 'geopolitical', 'China-Taiwan Rivalry', '{CHN}', '{TWN}', 'active', 'high', '1949-10-01', 'Sovereignty dispute and military pressure'),
('rel_078', 'rivalry', 'geopolitical', 'China-Philippines Rivalry', '{CHN}', '{PHL}', 'active', 'medium', '2012-04-08', 'South China Sea territorial competition'),
('rel_079', 'rivalry', 'geopolitical', 'China-Vietnam Rivalry', '{CHN}', '{VNM}', 'active', 'medium', '1979-02-17', 'Maritime disputes and regional influence contest'),
('rel_080', 'rivalry', 'geopolitical', 'China-Australia Rivalry', '{AUS}', '{CHN}', 'active', 'medium', '2020-01-01', 'Strategic competition despite economic ties'),
('rel_081', 'rivalry', 'geopolitical', 'United States-Iran Rivalry', '{IRN}', '{USA}', 'active', 'high', '1979-11-04', 'Long-term confrontation over regional security'),
('rel_082', 'rivalry', 'geopolitical', 'United States-North Korea Rivalry', '{PRK}', '{USA}', 'active', 'high', '1950-06-25', 'Nuclear deterrence and military tensions'),
('rel_083', 'rivalry', 'geopolitical', 'Russia-United Kingdom Rivalry', '{GBR}', '{RUS}', 'active', 'medium', '2018-03-04', 'Security confrontation intensified after Salisbury'),
('rel_084', 'rivalry', 'geopolitical', 'Russia-Poland Rivalry', '{POL}', '{RUS}', 'active', 'high', '2014-02-20', 'Regional security and historical disputes'),
('rel_085', 'rivalry', 'geopolitical', 'Russia-Baltic States Rivalry', '{EST,LVA,LTU}', '{RUS}', 'active', 'high', '2014-02-20', 'Persistent security competition in Baltic region'),
('rel_086', 'rivalry', 'geopolitical', 'Russia-NATO Rivalry', '{RUS}', '{ALB,BEL,BGR,CAN,HRV,CZE,DNK,EST,FIN,FRA,DEU,GRC,HUN,ISL,ITA,LVA,LTU,LUX,MNE,NLD,MKD,NOR,POL,PRT,ROU,SVK,SVN,ESP,SWE,TUR,GBR,USA}', 'active', 'high', '2014-02-20', 'Military and strategic confrontation in Europe'),
('rel_087', 'rivalry', 'geopolitical', 'Turkey-France Rivalry', '{FRA}', '{TUR}', 'active', 'medium', '2020-01-01', 'Competing interests in Mediterranean and Africa'),
('rel_088', 'rivalry', 'geopolitical', 'Turkey-United Arab Emirates Rivalry', '{ARE}', '{TUR}', 'active', 'low', '2011-01-01', 'Reduced but continuing regional competition'),
('rel_089', 'rivalry', 'geopolitical', 'Egypt-Ethiopia Rivalry', '{EGY}', '{ETH}', 'active', 'medium', '2011-04-02', 'Disputes over Nile waters and GERD project'),
('rel_090', 'rivalry', 'geopolitical', 'Rwanda-DR Congo Rivalry', '{COD}', '{RWA}', 'active', 'high', '2021-11-07', 'Regional competition linked to eastern Congo conflict'),
('rel_091', 'rivalry', 'geopolitical', 'Serbia-Kosovo Rivalry', '{SRB}', '{XKX}', 'active', 'high', '2008-02-17', 'Status dispute and recurring regional tensions'),
('rel_092', 'rivalry', 'geopolitical', 'Venezuela-Guyana Rivalry', '{GUY}', '{VEN}', 'active', 'high', '1966-05-26', 'Escalating dispute over Essequibo region'),
('rel_093', 'rivalry', 'geopolitical', 'China-European Union Rivalry', '{CHN}', '{AUT,BEL,BGR,HRV,CYP,CZE,DNK,EST,FIN,FRA,DEU,GRC,HUN,IRL,ITA,LVA,LTU,LUX,MLT,NLD,POL,PRT,ROU,SVK,SVN,ESP,SWE}', 'active', 'medium', '2019-03-12', 'Competition in trade, technology and influence'),
('rel_094', 'rivalry', 'geopolitical', 'Saudi Arabia-Qatar Rivalry', '{QAT}', '{SAU}', 'active', 'low', '1995-06-27', 'Historic Gulf competition despite reconciliation'),
('rel_095', 'rivalry', 'geopolitical', 'Algeria-France Rivalry', '{DZA}', '{FRA}', 'active', 'medium', '1962-07-05', 'Recurring disputes over history and influence'),
('rel_096', 'tension', 'territorial', 'South China Sea Dispute', '{CHN}', '{PHL,VNM,MYS,BRN,TWN}', 'active', 'high', '1947-01-01', 'Competing maritime and island sovereignty claims'),
('rel_097', 'tension', 'territorial', 'East China Sea Dispute', '{CHN}', '{JPN,TWN}', 'active', 'high', '1971-01-01', 'Dispute over Senkaku/Diaoyu Islands'),
('rel_098', 'tension', 'territorial', 'Taiwan Strait Sovereignty Dispute', '{CHN}', '{TWN}', 'active', 'high', '1949-10-01', 'Beijing claims Taiwan as part of China'),
('rel_099', 'tension', 'territorial', 'Kashmir Territorial Dispute', '{IND}', '{PAK}', 'active', 'high', '1947-10-22', 'Competing claims over Jammu and Kashmir'),
('rel_100', 'tension', 'territorial', 'Aksai Chin Dispute', '{CHN}', '{IND}', 'active', 'high', '1962-11-21', 'Unresolved Himalayan border dispute'),
('rel_101', 'tension', 'territorial', 'Arunachal Pradesh Dispute', '{CHN}', '{IND}', 'active', 'high', '1951-01-01', 'China claims Indian-administered territory'),
('rel_102', 'tension', 'territorial', 'Western Sahara Dispute', '{MAR}', '{ESH}', 'active', 'high', '1975-11-06', 'Sovereignty dispute over Western Sahara'),
('rel_103', 'tension', 'territorial', 'Kosovo Status Dispute', '{SRB}', '{XKX}', 'active', 'high', '2008-02-17', 'Serbia rejects Kosovo independence'),
('rel_104', 'tension', 'territorial', 'Northern Cyprus Dispute', '{CYP}', '{TUR}', 'active', 'medium', '1974-07-20', 'Division of Cyprus remains unresolved'),
('rel_105', 'tension', 'territorial', 'Aegean Sea Maritime Dispute', '{GRC}', '{TUR}', 'active', 'high', '1973-11-01', 'Disputes over waters, airspace and islands'),
('rel_106', 'tension', 'territorial', 'Eastern Mediterranean EEZ Dispute', '{GRC,CYP}', '{TUR}', 'active', 'high', '2019-11-27', 'Competing maritime boundary claims'),
('rel_107', 'tension', 'territorial', 'Kuril Islands Dispute', '{JPN}', '{RUS}', 'active', 'medium', '1945-09-02', 'No peace treaty due to island dispute'),
('rel_108', 'tension', 'territorial', 'Dokdo-Takeshima Dispute', '{KOR}', '{JPN}', 'active', 'medium', '1952-01-18', 'Competing claims over islets in Sea of Japan'),
('rel_109', 'tension', 'territorial', 'Siachen Glacier Dispute', '{IND}', '{PAK}', 'active', 'medium', '1984-04-13', 'Military deployment in disputed glacier region'),
('rel_110', 'tension', 'territorial', 'Sir Creek Dispute', '{IND}', '{PAK}', 'active', 'low', '1965-01-01', 'Maritime boundary disagreement in Arabian Sea'),
('rel_111', 'tension', 'territorial', 'Armenia-Azerbaijan Border Dispute', '{ARM}', '{AZE}', 'active', 'high', '1991-12-26', 'Demarcation disputes after Karabakh wars'),
('rel_112', 'tension', 'territorial', 'Transnistria Status Dispute', '{MDA}', '{PMR}', 'active', 'medium', '1992-07-21', 'Separatist territory remains unresolved'),
('rel_113', 'tension', 'territorial', 'Abkhazia Status Dispute', '{GEO}', '{ABK}', 'active', 'medium', '2008-08-26', 'Georgia rejects Abkhaz independence'),
('rel_114', 'tension', 'territorial', 'South Ossetia Status Dispute', '{GEO}', '{OST}', 'active', 'medium', '2008-08-26', 'Georgia rejects South Ossetian independence'),
('rel_115', 'tension', 'territorial', 'Crimea Sovereignty Dispute', '{UKR}', '{RUS}', 'active', 'high', '2014-03-18', 'Ukraine and most states reject annexation'),
('rel_116', 'tension', 'territorial', 'Donbas Territorial Dispute', '{UKR}', '{RUS}', 'active', 'high', '2014-04-07', 'Competing claims over occupied territories'),
('rel_117', 'tension', 'territorial', 'Venezuela-Guyana Essequibo Dispute', '{VEN}', '{GUY}', 'active', 'high', '1966-05-26', 'Dispute over resource-rich Essequibo region'),
('rel_118', 'tension', 'territorial', 'Belize-Guatemala Territorial Dispute', '{BLZ}', '{GTM}', 'active', 'low', '1981-09-21', 'Unresolved border claim under ICJ review'),
('rel_119', 'tension', 'territorial', 'Falkland Islands Sovereignty Dispute', '{ARG}', '{GBR}', 'active', 'medium', '1833-01-03', 'Argentina claims British-administered islands'),
('rel_120', 'tension', 'territorial', 'Gibraltar Sovereignty Dispute', '{ESP}', '{GBR}', 'active', 'low', '1713-07-13', 'Spain maintains claim over Gibraltar'),
('rel_121', 'tension', 'territorial', 'Ceuta and Melilla Dispute', '{ESP}', '{MAR}', 'active', 'low', '1956-04-07', 'Morocco claims Spanish North African enclaves'),
('rel_122', 'tension', 'territorial', 'China-Bhutan Border Dispute', '{BTN}', '{CHN}', 'active', 'medium', '1959-01-01', 'Unresolved Himalayan territorial claims'),
('rel_123', 'tension', 'territorial', 'China-Nepal Border Frictions', '{CHN}', '{NPL}', 'active', 'low', '2020-01-01', 'Periodic disagreements over border alignment'),
('rel_124', 'tension', 'territorial', 'China-Mongolia Border Claim Issues', '{CHN}', '{MNG}', 'active', 'low', '1949-10-01', 'Residual nationalist territorial narratives'),
('rel_125', 'tension', 'territorial', 'North Korea-South Korea Maritime Dispute', '{PRK}', '{KOR}', 'active', 'medium', '1953-07-27', 'Disagreement over Northern Limit Line'),
('rel_126', 'tension', 'territorial', 'Sudan-South Sudan Abyei Dispute', '{SDN}', '{SSD}', 'active', 'medium', '2011-07-09', 'Status of Abyei area remains unresolved'),
('rel_127', 'tension', 'territorial', 'Ethiopia-Somalia Somaliland MoU Dispute', '{ETH}', '{SOM}', 'active', 'medium', '2024-01-01', 'Disagreement over Red Sea access arrangement'),
('rel_128', 'tension', 'territorial', 'Russia-Norway Svalbard Dispute', '{NOR}', '{RUS}', 'active', 'low', '1920-02-09', 'Differing interpretations of Svalbard Treaty'),
('rel_129', 'tension', 'territorial', 'Slovenia-Croatia Maritime Dispute', '{HRV}', '{SVN}', 'active', 'low', '1991-06-25', 'Bay of Piran maritime boundary disagreement'),
('rel_130', 'tension', 'territorial', 'Mauritius-United Kingdom Chagos Dispute', '{MUS}', '{GBR}', 'active', 'medium', '1965-11-08', 'Sovereignty transfer process remains incomplete'),
('rel_131', 'alliance', 'economic_political', 'European Union', '{AUT,BEL,BGR,HRV,CYP,CZE,DNK,EST,FIN,FRA,DEU,GRC,HUN,IRL,ITA,LVA,LTU,LUX,MLT,NLD,POL,PRT,ROU,SVK,SVN,ESP,SWE}', NULL, 'active', 'high', '1993-11-01', 'Political and economic union with single market'),
('rel_132', 'alliance', 'economic', 'European Economic Area', '{ISL,LIE,NOR,AUT,BEL,BGR,HRV,CYP,CZE,DNK,EST,FIN,FRA,DEU,GRC,HUN,IRL,ITA,LVA,LTU,LUX,MLT,NLD,POL,PRT,ROU,SVK,SVN,ESP,SWE}', NULL, 'active', 'high', '1994-01-01', 'Extends EU single market to EFTA members'),
('rel_133', 'alliance', 'economic', 'European Free Trade Association', '{ISL,LIE,NOR,CHE}', NULL, 'active', 'medium', '1960-05-03', 'Free trade bloc outside the EU'),
('rel_134', 'alliance', 'economic', 'Eurozone', '{AUT,BEL,HRV,CYP,EST,FIN,FRA,DEU,GRC,IRL,ITA,LVA,LTU,LUX,MLT,NLD,PRT,SVK,SVN,ESP}', NULL, 'active', 'high', '1999-01-01', 'Monetary union using the euro currency'),
('rel_135', 'alliance', 'economic_political', 'Association of Southeast Asian Nations (ASEAN)', '{BRN,KHM,IDN,LAO,MYS,MMR,PHL,SGP,THA,VNM}', NULL, 'active', 'high', '1967-08-08', 'Regional political and economic organization'),
('rel_136', 'alliance', 'economic', 'ASEAN Free Trade Area', '{BRN,KHM,IDN,LAO,MYS,MMR,PHL,SGP,THA,VNM}', NULL, 'active', 'high', '1992-01-28', 'Tariff reduction and trade integration framework'),
('rel_137', 'alliance', 'economic_political', 'African Union', '{DZA,AGO,BEN,BWA,BFA,BDI,CMR,CPV,CAF,TCD,COM,COD,COG,CIV,DJI,EGY,GNQ,ERI,SWZ,ETH,GAB,GMB,GHA,GIN,GNB,KEN,LSO,LBR,LBY,MDG,MWI,MLI,MRT,MUS,MAR,MOZ,NAM,NER,NGA,RWA,STP,SEN,SYC,SLE,SOM,ZAF,SSD,SDN,TZA,TGO,TUN,UGA,ZMB,ZWE}', NULL, 'active', 'high', '2002-07-09', 'Continental political and economic organization'),
('rel_138', 'alliance', 'economic', 'African Continental Free Trade Area', '{DZA,AGO,BEN,BWA,BFA,BDI,CMR,CPV,CAF,TCD,COM,COD,COG,CIV,DJI,EGY,GNQ,ERI,SWZ,ETH,GAB,GMB,GHA,GIN,GNB,KEN,LSO,LBR,LBY,MDG,MWI,MLI,MRT,MUS,MAR,MOZ,NAM,NER,NGA,RWA,STP,SEN,SYC,SLE,SOM,ZAF,SSD,SDN,TZA,TGO,TUN,UGA,ZMB,ZWE}', NULL, 'active', 'high', '2021-01-01', 'Continental free trade area under AU framework'),
('rel_139', 'alliance', 'economic', 'Southern African Customs Union', '{BWA,LSO,NAM,ZAF,SWZ}', NULL, 'active', 'medium', '1910-01-01', 'World oldest functioning customs union'),
('rel_140', 'alliance', 'economic', 'Common Market for Eastern and Southern Africa', '{BDI,COM,COD,DJI,EGY,SWZ,ETH,KEN,LBY,MDG,MWI,MUS,RWA,SYC,SDN,TUN,UGA,ZMB,ZWE}', NULL, 'active', 'medium', '1994-12-08', 'Regional common market in eastern and southern Africa'),
('rel_141', 'alliance', 'economic', 'East African Community', '{BDI,COD,KEN,RWA,SOM,SSD,TZA,UGA}', NULL, 'active', 'high', '2000-07-07', 'Regional common market and customs union'),
('rel_142', 'alliance', 'economic', 'Economic Community of West African States', '{BEN,BFA,CPV,CIV,GMB,GHA,GIN,GNB,LBR,MLI,NER,NGA,SEN,SLE,TGO}', NULL, 'active', 'high', '1975-05-28', 'Regional economic integration organization'),
('rel_143', 'alliance', 'economic', 'Southern African Development Community', '{AGO,BWA,COM,COD,SWZ,LSO,MDG,MWI,MUS,MOZ,NAM,SYC,ZAF,TZA,ZMB,ZWE}', NULL, 'active', 'medium', '1992-08-17', 'Regional economic cooperation bloc'),
('rel_144', 'alliance', 'economic', 'Intergovernmental Authority on Development', '{DJI,ETH,KEN,SOM,SSD,SDN,UGA,ERI}', NULL, 'active', 'medium', '1996-03-21', 'Regional development and economic cooperation'),
('rel_145', 'alliance', 'economic', 'Economic Community of Central African States', '{AGO,BDI,CMR,CAF,TCD,COD,COG,GNQ,GAB,RWA,STP}', NULL, 'active', 'medium', '1983-10-18', 'Central African economic integration bloc'),
('rel_146', 'alliance', 'economic', 'Gulf Cooperation Council', '{BHR,KWT,OMN,QAT,SAU,ARE}', NULL, 'active', 'high', '1981-05-25', 'Economic and political integration among Gulf monarchies'),
('rel_147', 'alliance', 'economic', 'Mercosur', '{ARG,BOL,BRA,PRY,URY}', NULL, 'active', 'high', '1991-03-26', 'South American customs union and common market'),
('rel_148', 'alliance', 'economic', 'Pacific Alliance', '{CHL,COL,MEX,PER}', NULL, 'active', 'medium', '2011-04-28', 'Latin American free trade and integration bloc'),
('rel_149', 'alliance', 'economic', 'Andean Community', '{BOL,COL,ECU,PER}', NULL, 'active', 'medium', '1969-05-26', 'Regional customs and economic integration group'),
('rel_150', 'alliance', 'economic', 'Central American Integration System', '{BLZ,CRI,SLV,GTM,HND,NIC,PAN,DOM}', NULL, 'active', 'medium', '1991-12-13', 'Economic and political integration framework'),
('rel_151', 'alliance', 'economic', 'Central American Common Market', '{CRI,SLV,GTM,HND,NIC}', NULL, 'active', 'medium', '1960-12-13', 'Regional common market in Central America'),
('rel_152', 'alliance', 'economic', 'United States-Mexico-Canada Agreement', '{CAN,MEX,USA}', NULL, 'active', 'high', '2020-07-01', 'North American free trade agreement'),
('rel_153', 'alliance', 'economic', 'Comprehensive and Progressive Agreement for Trans-Pacific Partnership', '{AUS,BRN,CAN,CHL,JPN,MYS,MEX,NZL,PER,SGP,GBR,VNM}', NULL, 'active', 'high', '2018-12-30', 'Major Asia-Pacific free trade agreement'),
('rel_154', 'alliance', 'economic', 'Regional Comprehensive Economic Partnership', '{AUS,BRN,KHM,CHN,IDN,JPN,LAO,MYS,MMR,NZL,PHL,SGP,KOR,THA,VNM}', NULL, 'active', 'high', '2022-01-01', 'Largest multilateral free trade agreement'),
('rel_155', 'alliance', 'economic', 'South Asian Free Trade Area', '{AFG,BGD,BTN,IND,MDV,NPL,PAK,LKA}', NULL, 'active', 'medium', '2006-01-01', 'Regional trade liberalization framework'),
('rel_156', 'alliance', 'economic_political', 'Shanghai Cooperation Organization', '{BLR,CHN,IND,IRN,KAZ,KGZ,PAK,RUS,TJK,UZB}', NULL, 'active', 'medium', '2001-06-15', 'Eurasian cooperation with economic dimension'),
('rel_157', 'alliance', 'economic', 'Eurasian Economic Union', '{ARM,BLR,KAZ,KGZ,RUS}', NULL, 'active', 'high', '2015-01-01', 'Customs and economic union in Eurasia'),
('rel_158', 'alliance', 'economic', 'Economic Cooperation Organization', '{AFG,AZE,IRN,KAZ,KGZ,PAK,TJK,TKM,TUR,UZB}', NULL, 'active', 'medium', '1985-01-01', 'Regional trade and development organization'),
('rel_159', 'alliance', 'economic_political', 'BRICS', '{BRA,RUS,IND,CHN,ZAF,EGY,ETH,IDN,IRN,SAU,ARE}', NULL, 'active', 'high', '2009-06-16', 'Major emerging economies coordination bloc'),
('rel_160', 'alliance', 'economic_political', 'Organization of Turkic States', '{AZE,KAZ,KGZ,TUR,UZB}', NULL, 'active', 'medium', '2009-10-03', 'Economic and political cooperation among Turkic states'),
('rel_161', 'tension', 'diplomatic', 'United States-Iran Sanctions Crisis', '{USA}', '{IRN}', 'active', 'high', '2018-05-08', 'Extensive sanctions and diplomatic confrontation'),
('rel_162', 'tension', 'diplomatic', 'Russia-West Diplomatic Crisis', '{RUS}', '{USA,CAN,GBR,FRA,DEU,ITA,JPN,AUS,EU}', 'active', 'high', '2022-02-24', 'Sanctions, expulsions and political isolation'),
('rel_163', 'tension', 'diplomatic', 'United States-China Diplomatic Tensions', '{USA}', '{CHN}', 'active', 'high', '2018-03-22', 'Trade, technology and security disputes'),
('rel_164', 'tension', 'diplomatic', 'China-Taiwan Diplomatic Crisis', '{CHN}', '{TWN}', 'active', 'high', '1949-10-01', 'Persistent sovereignty and recognition dispute'),
('rel_165', 'tension', 'diplomatic', 'China-Lithuania Diplomatic Dispute', '{CHN}', '{LTU}', 'active', 'medium', '2021-11-18', 'Dispute related to Taiwan representation'),
('rel_166', 'tension', 'diplomatic', 'European Union-Belarus Diplomatic Crisis', '{BLR}', '{AUT,BEL,BGR,HRV,CYP,CZE,DNK,EST,FIN,FRA,DEU,GRC,HUN,IRL,ITA,LVA,LTU,LUX,MLT,NLD,POL,PRT,ROU,SVK,SVN,ESP,SWE}', 'active', 'high', '2020-08-09', 'Sanctions over governance and security issues'),
('rel_167', 'tension', 'diplomatic', 'Belarus-Poland Border Crisis', '{BLR}', '{POL}', 'active', 'medium', '2021-07-01', 'Migration and border security dispute'),
('rel_168', 'tension', 'diplomatic', 'Belarus-Lithuania Border Crisis', '{BLR}', '{LTU}', 'active', 'medium', '2021-07-01', 'Migration-related diplomatic tensions'),
('rel_169', 'tension', 'diplomatic', 'North Korea-United States Diplomatic Standoff', '{PRK}', '{USA}', 'active', 'high', '2017-01-01', 'Nuclear program and sanctions dispute'),
('rel_170', 'tension', 'diplomatic', 'North Korea-Japan Diplomatic Dispute', '{JPN}', '{PRK}', 'active', 'medium', '2002-09-17', 'Missile launches and abduction issues'),
('rel_171', 'tension', 'diplomatic', 'North Korea-South Korea Diplomatic Crisis', '{KOR}', '{PRK}', 'active', 'high', '2020-06-16', 'Military incidents and frozen dialogue'),
('rel_172', 'tension', 'diplomatic', 'Iran-Israel Diplomatic Confrontation', '{IRN}', '{ISR}', 'active', 'high', '1979-02-11', 'No diplomatic relations and mutual hostility'),
('rel_173', 'tension', 'diplomatic', 'Iran-United Kingdom Diplomatic Tensions', '{GBR}', '{IRN}', 'active', 'medium', '2019-07-04', 'Sanctions and maritime security disputes'),
('rel_174', 'tension', 'diplomatic', 'Iran-France Diplomatic Tensions', '{FRA}', '{IRN}', 'active', 'medium', '2018-05-08', 'Nuclear program and sanctions disagreements'),
('rel_175', 'tension', 'diplomatic', 'Iran-Germany Diplomatic Tensions', '{DEU}', '{IRN}', 'active', 'medium', '2018-05-08', 'Sanctions and security concerns'),
('rel_176', 'tension', 'diplomatic', 'Iran-Canada Diplomatic Rupture', '{CAN}', '{IRN}', 'active', 'medium', '2012-09-07', 'Diplomatic relations remain suspended'),
('rel_177', 'tension', 'diplomatic', 'Israel-South Africa Diplomatic Crisis', '{ISR}', '{ZAF}', 'active', 'high', '2023-12-29', 'Severe dispute related to Gaza conflict'),
('rel_178', 'tension', 'diplomatic', 'Israel-Turkey Diplomatic Tensions', '{ISR}', '{TUR}', 'active', 'medium', '2023-10-07', 'Relations deteriorated after Gaza war'),
('rel_179', 'tension', 'diplomatic', 'Israel-Colombia Diplomatic Crisis', '{COL}', '{ISR}', 'active', 'medium', '2024-05-01', 'Diplomatic relations significantly downgraded'),
('rel_180', 'tension', 'diplomatic', 'India-Canada Diplomatic Crisis', '{CAN}', '{IND}', 'active', 'high', '2023-09-18', 'Mutual accusations and diplomatic expulsions'),
('rel_181', 'tension', 'diplomatic', 'India-Pakistan Diplomatic Crisis', '{IND}', '{PAK}', 'active', 'high', '2019-08-05', 'Relations downgraded over Kashmir'),
('rel_182', 'tension', 'diplomatic', 'Pakistan-Afghanistan Diplomatic Tensions', '{AFG}', '{PAK}', 'active', 'medium', '2021-08-15', 'Border security and militant disputes'),
('rel_183', 'tension', 'diplomatic', 'Afghanistan-Tajikistan Diplomatic Tensions', '{AFG}', '{TJK}', 'active', 'medium', '2021-08-15', 'Recognition and border security disagreements'),
('rel_184', 'tension', 'diplomatic', 'China-Philippines Diplomatic Crisis', '{CHN}', '{PHL}', 'active', 'high', '2023-01-01', 'Escalating disputes in South China Sea'),
('rel_185', 'tension', 'diplomatic', 'China-Australia Diplomatic Tensions', '{AUS}', '{CHN}', 'active', 'medium', '2020-04-21', 'Strategic distrust despite partial normalization'),
('rel_186', 'tension', 'diplomatic', 'China-Japan Diplomatic Tensions', '{CHN}', '{JPN}', 'active', 'medium', '2012-09-11', 'Maritime and security disputes'),
('rel_187', 'tension', 'diplomatic', 'China-European Union Diplomatic Tensions', '{CHN}', '{AUT,BEL,BGR,HRV,CYP,CZE,DNK,EST,FIN,FRA,DEU,GRC,HUN,IRL,ITA,LVA,LTU,LUX,MLT,NLD,POL,PRT,ROU,SVK,SVN,ESP,SWE}', 'active', 'medium', '2019-03-12', 'Trade, security and human rights disputes'),
('rel_188', 'tension', 'diplomatic', 'Venezuela-United States Diplomatic Crisis', '{USA}', '{VEN}', 'active', 'high', '2019-01-23', 'Sanctions and limited diplomatic engagement'),
('rel_189', 'tension', 'diplomatic', 'Venezuela-Guyana Diplomatic Crisis', '{VEN}', '{GUY}', 'active', 'high', '2023-12-03', 'Essequibo dispute drives bilateral tensions'),
('rel_190', 'tension', 'diplomatic', 'Morocco-Algeria Diplomatic Rupture', '{DZA}', '{MAR}', 'active', 'high', '2021-08-24', 'Formal diplomatic relations remain severed'),
('rel_191', 'tension', 'diplomatic', 'Algeria-France Diplomatic Tensions', '{DZA}', '{FRA}', 'active', 'medium', '2021-10-02', 'Historical memory and migration disputes'),
('rel_192', 'tension', 'diplomatic', 'Mali-France Diplomatic Crisis', '{FRA}', '{MLI}', 'active', 'medium', '2022-01-31', 'Military withdrawal and political disagreements'),
('rel_193', 'tension', 'diplomatic', 'Niger-France Diplomatic Crisis', '{FRA}', '{NER}', 'active', 'medium', '2023-07-26', 'Post-coup diplomatic breakdown'),
('rel_194', 'tension', 'diplomatic', 'Burkina Faso-France Diplomatic Crisis', '{BFA}', '{FRA}', 'active', 'medium', '2022-01-24', 'Security cooperation largely terminated'),
('rel_195', 'tension', 'diplomatic', 'European Union-Hungary Rule of Law Dispute', '{HUN}', '{AUT,BEL,BGR,HRV,CYP,CZE,DNK,EST,FIN,FRA,DEU,GRC,IRL,ITA,LVA,LTU,LUX,MLT,NLD,POL,PRT,ROU,SVK,SVN,ESP,SWE}', 'active', 'medium', '2022-09-18', 'Funding and governance disagreements'),
('rel_196', 'tension', 'diplomatic', 'Serbia-Kosovo Diplomatic Crisis', '{SRB}', '{XKX}', 'active', 'high', '2008-02-17', 'Normalization process remains unresolved'),
('rel_197', 'tension', 'diplomatic', 'Russia-Moldova Diplomatic Tensions', '{MDA}', '{RUS}', 'active', 'high', '2022-02-24', 'Security concerns linked to Transnistria'),
('rel_198', 'tension', 'diplomatic', 'Russia-Czech Republic Diplomatic Crisis', '{CZE}', '{RUS}', 'active', 'medium', '2021-04-17', 'Mutual expulsions and reduced relations'),
('rel_199', 'tension', 'diplomatic', 'Russia-United Kingdom Diplomatic Crisis', '{GBR}', '{RUS}', 'active', 'high', '2018-03-04', 'Sanctions and persistent political confrontation'),
('rel_200', 'tension', 'diplomatic', 'Russia-Poland Diplomatic Crisis', '{POL}', '{RUS}', 'active', 'high', '2022-02-24', 'Severe deterioration of bilateral relations');