import { getDataset, owidKey } from '../lib/datasets'

/**
 * Loads OWID historical data through the unified dataset layer: Supabase
 * snapshot first, falling back to the pre-downloaded files in
 * /public/data/historical/ (generated by: node scripts/fetch-historical.mjs).
 *
 * Data shape either way: { "<year>": { "<ISO2>": <value>, ... }, ... }
 */
export function fetchOwidHistorical(chartSlug) {
  return getDataset(owidKey(chartSlug), async () => {
    const url = `/data/historical/${chartSlug}.json`
    const res = await fetch(url)
    if (!res.ok) throw new Error(
      `Historical data not found for "${chartSlug}". ` +
      `Run: node scripts/fetch-historical.mjs`
    )
    return res.json()
  })
}
