/**
 * Loads pre-downloaded OWID historical data from /public/data/historical/.
 *
 * Data files are generated by running:  node scripts/fetch-historical.mjs
 * Each file has the shape: { "<year>": { "<ISO2>": <value>, ... }, ... }
 */
export async function fetchOwidHistorical(chartSlug) {
  const url = `/data/historical/${chartSlug}.json`
  const res = await fetch(url)
  if (!res.ok) throw new Error(
    `Historical data not found for "${chartSlug}". ` +
    `Run: node scripts/fetch-historical.mjs`
  )
  return res.json()
}
