export const LAYERS = {
  // ── Existing layers ──────────────────────────────────────────────────
  geographic: { label: 'Geographic', property: null, unit: '', source: 'none' },
  political:  { label: 'Political',  property: null, unit: '', source: 'static' },
  population: {
    label: 'Population',
    indicator: 'SP.POP.TOTL',
    unit: 'people',
    source: 'worldbank',
    format: 'integer',
    scale: 'log',
    attribution: 'World Bank',
    historical: {
      owidChart: 'population',
      yearRange: [1700, 2016],
      defaultYear: 2016,
      attribution: 'OWID / Gapminder · UN',
    },
  },
  area: {
    label: 'Area',
    indicator: 'AG.SRF.TOTL.K2',
    unit: 'km²',
    source: 'worldbank',
    format: 'integer',
    scale: 'log',
    attribution: 'World Bank',
  },

  // ── World Bank layers ────────────────────────────────────────────────
  gdp_per_capita: {
    label: 'GDP per Capita',
    indicator: 'NY.GDP.PCAP.CD',
    unit: 'USD',
    source: 'worldbank',
    format: 'currency',
    attribution: 'World Bank',
    historical: {
      owidChart: 'gdp-per-capita-maddison',
      yearRange: [1800, 2018],
      defaultYear: 2018,
      attribution: 'OWID / Maddison Project',
    },
  },
  gdp_growth: {
    label: 'GDP Growth',
    indicator: 'NY.GDP.MKTP.KD.ZG',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    attribution: 'World Bank',
  },
  unemployment: {
    label: 'Unemployment',
    indicator: 'SL.UEM.TOTL.ZS',
    unit: '% of labor force',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    invert: true,
    attribution: 'World Bank',
  },
  life_expectancy: {
    label: 'Life Expectancy',
    indicator: 'SP.DYN.LE00.IN',
    unit: 'years',
    source: 'worldbank',
    format: 'decimal',
    scale: 'linear',
    attribution: 'World Bank',
    historical: {
      owidChart: 'life-expectancy',
      yearRange: [1800, 2015],
      defaultYear: 2015,
      attribution: 'OWID / Gapminder · UN',
    },
  },
  military_spending: {
    label: 'Military Spending',
    indicator: 'MS.MIL.XPND.GD.ZS',
    unit: '% of GDP',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    invert: true,
    attribution: 'World Bank',
  },
  electricity_access: {
    label: 'Electricity Access',
    indicator: 'EG.ELC.ACCS.ZS',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    attribution: 'World Bank',
  },
  gini_index: {
    label: 'Gini Index',
    indicator: 'SI.POV.GINI',
    unit: '',
    source: 'worldbank',
    format: 'decimal',
    scale: 'linear',
    invert: true,
    mrv: 10,
    attribution: 'World Bank',
  },
  literacy_rate: {
    label: 'Literacy Rate',
    indicator: 'SE.ADT.LITR.ZS',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    mrv: 30,
    fallback: 99,
    supplementalFetch: true,
    attribution: 'World Bank',
  },
  internet_users: {
    label: 'Internet Users',
    indicator: 'IT.NET.USER.ZS',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    attribution: 'World Bank',
  },
  renewable_energy: {
    label: 'Renewable Energy',
    indicator: 'EG.FEC.RNEW.ZS',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    mrv: 10,
    attribution: 'World Bank',
  },
  inflation: {
    label: 'Inflation',
    indicator: 'FP.CPI.TOTC.ZG',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    invert: true,
    attribution: 'World Bank',
  },
  public_debt: {
    label: 'Public Debt',
    indicator: 'GC.DOD.TOTL.GD.ZS',
    unit: '% of GDP',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    invert: true,
    attribution: 'World Bank',
  },
  fiscal_balance: {
    label: 'Fiscal Balance',
    indicator: 'GC.NLD.TOTL.GD.ZS',
    unit: '% of GDP',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    attribution: 'World Bank',
  },
  birth_rate: {
    label: 'Birth Rate',
    indicator: 'SP.DYN.CBRT.IN',
    unit: 'per 1,000',
    source: 'worldbank',
    format: 'decimal',
    scale: 'linear',
    attribution: 'World Bank',
  },
  death_rate: {
    label: 'Death Rate',
    indicator: 'SP.DYN.CDRT.IN',
    unit: 'per 1,000',
    source: 'worldbank',
    format: 'decimal',
    scale: 'linear',
    invert: true,
    attribution: 'World Bank',
  },
  net_migration: {
    label: 'Net Migration',
    indicator: 'SM.POP.NETM',
    unit: 'people',
    source: 'worldbank',
    format: 'integer',
    scale: 'linear',
    mrv: 5,
    attribution: 'World Bank',
  },
  exports: {
    label: 'Exports',
    indicator: 'NE.EXP.GNFS.ZS',
    unit: '% of GDP',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    attribution: 'World Bank',
  },
  imports: {
    label: 'Imports',
    indicator: 'NE.IMP.GNFS.ZS',
    unit: '% of GDP',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    attribution: 'World Bank',
  },
  education_spending: {
    label: 'Education Spending',
    indicator: 'SE.XPD.TOTL.GD.ZS',
    unit: '% of GDP',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    mrv: 10,
    attribution: 'World Bank',
  },
  health_spending: {
    label: 'Health Spending',
    indicator: 'SH.XPD.CHEX.GD.ZS',
    unit: '% of GDP',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    attribution: 'World Bank',
  },
  water_access: {
    label: 'Water Access',
    indicator: 'SH.H2O.BASW.ZS',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    mrv: 10,
    attribution: 'World Bank',
  },
  co2_total: {
    label: 'CO₂ Emissions (total)',
    indicator: 'EN.ATM.CO2E.KT',
    unit: 'kt',
    source: 'worldbank',
    format: 'integer',
    scale: 'log',
    invert: true,
    mrv: 5,
    attribution: 'World Bank',
  },

  // ── Static dataset layers ────────────────────────────────────────────
  democracy_index: {
    label: 'Democracy Index',
    unit: 'V-Dem score',
    source: 'static',
    staticKey: 'vdem',
    format: 'decimal',
    scale: 'linear',
    attribution: 'V-Dem Institute',
  },

  // ── Diplomatic layers ────────────────────────────────────────────────
  alliances: {
    label: 'Alliances',
    source: 'diplomatic',
    attribution: 'COW Project',
  },
  trade: {
    label: 'Trade Routes',
    source: 'trade',
    attribution: 'CIA World Factbook',
  },
}

/**
 * Whether a layer can be added to a combined (multi-layer blend) selection.
 * Excludes historical layers (no single-year value to blend) and non-numeric
 * sources (political/geographic/alliances/trade), including `political`
 * itself which is `source: 'static'` but has no `staticKey`.
 */
export function isCombinableLayer(key) {
  const layer = LAYERS[key]
  if (!layer || layer.historical) return false
  if (layer.source === 'worldbank') return true
  if (layer.source === 'static') return !!layer.staticKey
  return false
}

export const SIDEBAR_INDICATORS = [
  { indicator: 'SP.POP.TOTL',         label: 'Population',          format: 'integer', unit: '' },
  { indicator: 'NY.GDP.PCAP.CD',      label: 'GDP per Capita',      format: 'currency', unit: 'USD' },
  { indicator: 'NY.GDP.MKTP.KD.ZG',  label: 'GDP Growth',          format: 'percent', unit: '%' },
  { indicator: 'SL.UEM.TOTL.ZS',     label: 'Unemployment',        format: 'percent', unit: '%' },
  { indicator: 'FP.CPI.TOTC.ZG',     label: 'Inflation',           format: 'percent', unit: '%' },
  { indicator: 'SI.POV.GINI',        label: 'Gini Index',          format: 'decimal', unit: '' },
  { indicator: 'SP.DYN.LE00.IN',     label: 'Life Expectancy',     format: 'decimal', unit: 'years' },
  { indicator: 'SE.ADT.LITR.ZS',     label: 'Literacy Rate',       format: 'percent', unit: '%' },
  { indicator: 'IT.NET.USER.ZS',     label: 'Internet Users',      format: 'percent', unit: '%' },
  { indicator: 'EG.ELC.ACCS.ZS',     label: 'Electricity Access',  format: 'percent', unit: '%' },
  { indicator: 'EG.FEC.RNEW.ZS',     label: 'Renewable Energy',    format: 'percent', unit: '%' },
  { indicator: 'EN.ATM.CO2E.PC',     label: 'CO₂ per Capita',      format: 'decimal', unit: 'tonnes' },
  { indicator: 'MS.MIL.XPND.GD.ZS', label: 'Military Spending',   format: 'percent', unit: '% of GDP' },
  { indicator: 'GC.DOD.TOTL.GD.ZS', label: 'Public Debt',         format: 'percent', unit: '% of GDP' },
  { indicator: 'GC.NLD.TOTL.GD.ZS', label: 'Fiscal Balance',      format: 'percent', unit: '% of GDP' },
  { indicator: 'SP.DYN.CBRT.IN',    label: 'Birth Rate',          format: 'decimal', unit: 'per 1,000' },
  { indicator: 'SP.DYN.CDRT.IN',    label: 'Death Rate',          format: 'decimal', unit: 'per 1,000' },
  { indicator: 'SM.POP.NETM',       label: 'Net Migration',       format: 'integer', unit: 'people' },
  { indicator: 'NE.EXP.GNFS.ZS',   label: 'Exports',             format: 'percent', unit: '% of GDP' },
  { indicator: 'NE.IMP.GNFS.ZS',   label: 'Imports',             format: 'percent', unit: '% of GDP' },
  { indicator: 'SE.XPD.TOTL.GD.ZS', label: 'Education Spending', format: 'percent', unit: '% of GDP' },
  { indicator: 'SH.XPD.CHEX.GD.ZS', label: 'Health Spending',    format: 'percent', unit: '% of GDP' },
  { indicator: 'SH.H2O.BASW.ZS',   label: 'Water Access',        format: 'percent', unit: '%' },
  { indicator: 'EN.ATM.CO2E.KT',   label: 'CO₂ Emissions',       format: 'integer', unit: 'kt' },
]
