export const LAYERS = {
  // ── Existing layers ──────────────────────────────────────────────────
  geographic: { label: 'Geographic', property: null, unit: '', source: 'none' },
  political:  { label: 'Political',  property: null, unit: '', source: 'static' },
  population: {
    label: 'Population',
    indicator: 'SP.POP.TOTL',
    unit: 'people',
    source: 'worldbank',
    format: 'integer',
    scale: 'log',
    attribution: 'World Bank',
  },
  area: {
    label: 'Area',
    indicator: 'AG.SRF.TOTL.K2',
    unit: 'km²',
    source: 'worldbank',
    format: 'integer',
    scale: 'log',
    attribution: 'World Bank',
  },

  // ── World Bank layers ────────────────────────────────────────────────
  gdp_per_capita: {
    label: 'GDP per Capita',
    indicator: 'NY.GDP.PCAP.CD',
    unit: 'USD',
    source: 'worldbank',
    format: 'currency',
    attribution: 'World Bank',
  },
  gdp_growth: {
    label: 'GDP Growth',
    indicator: 'NY.GDP.MKTP.KD.ZG',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    attribution: 'World Bank',
  },
  unemployment: {
    label: 'Unemployment',
    indicator: 'SL.UEM.TOTL.ZS',
    unit: '% of labor force',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    invert: true,
    attribution: 'World Bank',
  },
  life_expectancy: {
    label: 'Life Expectancy',
    indicator: 'SP.DYN.LE00.IN',
    unit: 'years',
    source: 'worldbank',
    format: 'decimal',
    scale: 'linear',
    attribution: 'World Bank',
  },
  military_spending: {
    label: 'Military Spending',
    indicator: 'MS.MIL.XPND.GD.ZS',
    unit: '% of GDP',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    invert: true,
    attribution: 'World Bank',
  },
  electricity_access: {
    label: 'Electricity Access',
    indicator: 'EG.ELC.ACCS.ZS',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    attribution: 'World Bank',
  },
  gini_index: {
    label: 'Gini Index',
    indicator: 'SI.POV.GINI',
    unit: '',
    source: 'worldbank',
    format: 'decimal',
    scale: 'linear',
    invert: true,
    mrv: 10,
    attribution: 'World Bank',
  },
  literacy_rate: {
    label: 'Literacy Rate',
    indicator: 'SE.ADT.LITR.ZS',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    mrv: 30,
    fallback: 99,
    supplementalFetch: true,
    attribution: 'World Bank',
  },
  internet_users: {
    label: 'Internet Users',
    indicator: 'IT.NET.USER.ZS',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    attribution: 'World Bank',
  },
  renewable_energy: {
    label: 'Renewable Energy',
    indicator: 'EG.FEC.RNEW.ZS',
    unit: '%',
    source: 'worldbank',
    format: 'percent',
    scale: 'linear',
    mrv: 10,
    attribution: 'World Bank',
  },

  // ── Static dataset layers ────────────────────────────────────────────
  democracy_index: {
    label: 'Democracy Index',
    unit: 'V-Dem score',
    source: 'static',
    staticKey: 'vdem',
    format: 'decimal',
    scale: 'linear',
    attribution: 'V-Dem Institute',
  },

  // ── Diplomatic layers ────────────────────────────────────────────────
  alliances: {
    label: 'Alliances',
    source: 'diplomatic',
    attribution: 'COW Project',
  },
  trade: {
    label: 'Trade Routes',
    source: 'trade',
    attribution: 'CIA World Factbook',
  },
}

export const SIDEBAR_INDICATORS = [
  { indicator: 'SP.POP.TOTL',         label: 'Population',          format: 'integer', unit: '' },
  { indicator: 'NY.GDP.PCAP.CD',      label: 'GDP per Capita',      format: 'currency', unit: 'USD' },
  { indicator: 'NY.GDP.MKTP.KD.ZG',  label: 'GDP Growth',          format: 'percent', unit: '%' },
  { indicator: 'SL.UEM.TOTL.ZS',     label: 'Unemployment',        format: 'percent', unit: '%' },
  { indicator: 'FP.CPI.TOTC.ZG',     label: 'Inflation',           format: 'percent', unit: '%' },
  { indicator: 'SI.POV.GINI',        label: 'Gini Index',          format: 'decimal', unit: '' },
  { indicator: 'SP.DYN.LE00.IN',     label: 'Life Expectancy',     format: 'decimal', unit: 'years' },
  { indicator: 'SE.ADT.LITR.ZS',     label: 'Literacy Rate',       format: 'percent', unit: '%' },
  { indicator: 'IT.NET.USER.ZS',     label: 'Internet Users',      format: 'percent', unit: '%' },
  { indicator: 'EG.ELC.ACCS.ZS',     label: 'Electricity Access',  format: 'percent', unit: '%' },
  { indicator: 'EG.FEC.RNEW.ZS',     label: 'Renewable Energy',    format: 'percent', unit: '%' },
  { indicator: 'EN.ATM.CO2E.PC',     label: 'CO₂ per Capita',      format: 'decimal', unit: 'tonnes' },
  { indicator: 'MS.MIL.XPND.GD.ZS', label: 'Military Spending',   format: 'percent', unit: '% of GDP' },
]
